[tool.poetry]
name = "space-polka"
version = "0.1"
description = "POLarimetry toolKit for Asteroids"
authors = ["Benoit Carry <benoit.carry@oca.eu>"]
license = "MIT"
readme = "README.md"
packages = [{'include' = 'polka'}]
